name: worshipsongs
description: Worship Songs

publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  carousel_slider: ^2.2.1
  http: ^0.12.2
  google_sign_in: ^4.5.1
  xml: ^4.1.0
  path_provider: ^1.6.11
  styled_text: ^1.0.1+1
  provider: ^4.3.2
  url_launcher: ^5.5.0
  shared_preferences: ^0.5.10

  firebase_core: ^0.4.0+9
  firebase_crashlytics: ^0.1.4+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/illustrations/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Regular.ttf
        - asset: assets/font/Rubik-Bold.ttf
          weight: 700
        - asset: assets/font/Rubik-Black.ttf
          weight: 900
        - asset: assets/font/Rubik-Medium.ttf
          weight: 500
