name: worshipsongs
description: Worship Songs

publish_to: 'none'

version: 0.3.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^0.19.0
  carousel_slider: ^2.2.1
  http: ^0.12.2
  path_provider: ^1.6.11
  styled_text: ^1.0.1+1
  provider: ^4.3.2
  url_launcher: ^5.5.0
  shared_preferences: ^0.5.10
  intl: ^0.16.1
  intl_translation: ^0.17.10+1
  modal_bottom_sheet: ^0.2.0+1
  package_info: ^0.4.3
  sticky_headers: ^0.1.8
  image_picker: ^0.6.6+5
  flutter_speed_dial: ^1.2.5
  flutter_auth_buttons: ^0.10.0
  readmore: ^1.0.0
  bloc: ^6.0.0
  flutter_bloc: ^6.0.6

  google_sign_in: ^4.5.4
  apple_sign_in: ^0.1.0
  firebase_auth: ^0.18.1+2
  crypto: ^2.1.5

  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.2.0
  firebase_storage: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_for_app_store.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/illustrations/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Regular.ttf
        - asset: assets/font/Rubik-Bold.ttf
          weight: 700
        - asset: assets/font/Rubik-Black.ttf
          weight: 900
        - asset: assets/font/Rubik-Medium.ttf
          weight: 500
