name: worshipsongs
description: Worship Songs

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  carousel_slider: ^2.2.1
  http: ^0.12.2
  google_sign_in: ^4.5.1
  xml: ^4.1.0
  path_provider: ^1.6.11
  styled_text: ^1.0.1+1

  firebase_core: ^0.4.0+9
  firebase_auth: ^0.16.1
  firebase_analytics: ^5.0.2
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.13.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/illustrations/

  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/font/MavenPro-Regular.ttf
        - asset: assets/font/MavenPro-Bold.ttf
          weight: 700
        - asset: assets/font/MavenPro-Black.ttf
          weight: 900
        - asset: assets/font/MavenPro-Medium.ttf
          weight: 500
